server:
  port: 8443
  http2:
    enabled: true
  ssl:
    key-store: classpath:jks/keystore.p12
    key-store-password: secret
    key-alias: tomcat
    key-store-type: PKCS12
spring:
  resources:
    cache:
      cachecontrol:
        max-age: 36000
        cache-public: true
emp:
  server: "https://localhost:8443"